cookie:
  expiry_days: 30
  key: random_signature_key
  name: random_cookie_name
credentials:
  usernames:
    shivam:
      email: shivam@dhnss.com
      first_name: Shivam
      last_name: hel
      logged_in: false
      password: $2b$12$bJo689kqRQAgOHsZkMt2/.cLg0bovSa.m.GGurjKVNFlplhywXly2
      roles: null
    shivansh:
      email: shivansh@gmail.com
      first_name: Dr
      last_name: Shivansh
      logged_in: false
      password: $2b$12$0hXjzWF5XYrcRRyjDb1T3.cZLPtRsD11RP.7aaewQMcFSH3YIIljO
      roles: null
    sidd:
      email: siddarth@gmail.com
      first_name: Dr
      last_name: Siddarth
      logged_in: false
      password: $2b$12$QZFn4OGkzxFY.D8aT4EPGeDgSFGobHLqBtye9Yzu5dswE/8I.OKvO
      password_hint: Shivansh@123
      roles: null
    siddarth:
      email: siddarth123@gmail.com
      first_name: Siddarth
      last_name: Baruah
      logged_in: false
      password: $2b$12$DlVLjn7b192CTKiw2AA88.43Q6D.a4w.Bs/q0rNZZaUhC2/Ju448C
      roles: null
preauthorized:
  emails:
  - melsby@gmail.com
